packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

# -------------------------------------------------------------------------
# PNPM Catalogs
# -------------------------------------------------------------------------
# Define strict versions for dependencies used across multiple packages.
#
# Referenced in package.json as: "dependency": "catalog:"
#
# Advantages:
# 1. Single Source of Truth: Update version in ONE place for the entire repo.
# 2. Deduplication: Guarantees every package uses the exact same version.
# 3. Consistency: Prevents mismatches between apps/packages.
# -------------------------------------------------------------------------
catalog:
  typescript: ^5.9.3
  effect: ^3.19.14
  zod: 4.3.1
  vite: ^7.2.4
  "react-hook-form": ^7.71.1
  "@hookform/resolvers": ^5.2.2
  "@biomejs/biome": ^2.3.11

catalogs:
  react19:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

  vitest3:
    "vitest": 4.0.17
    "@vitest/coverage-istanbul": 4.0.17
    "@vitest/coverage-v8": 4.0.17
    "@vitest/ui": 4.0.17

onlyBuiltDependencies:
  - esbuild
