packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.28.0
  prettier: ^3.7.4
  typescript: ^5.9.3
  effect: ^3.19.14
  zod: 4.3.1
  "react-hook-form": ^7.71.1
  "@hookform/resolvers": ^5.2.2

catalogs:
  react19:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

  vitest3:
    "vitest": 4.0.17
    "@vitest/coverage-istanbul": 4.0.17
    "@vitest/coverage-v8": 4.0.17
    "@vitest/ui": 4.0.17

onlyBuiltDependencies:
  - esbuild
